spin_manifest_version = 2

[application]
authors = ["Anya Gau <160428445+anyagau@users.noreply.github.com>"]
description = ""
name = "test13"
version = "0.1.0"

[[trigger.http]]
route = "/..."
component = "test13"

[component.test13]
source = "target/test13.wasm"
exclude_files = ["**/node_modules"]
[component.test13.build]
command = "npm run build"
watch = ["src/**/*.ts", "package.json"]
